name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  backend-checks:
    name: Backend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install backend dependencies
        working-directory: ./apps/backend
        run: npm ci

      - name: Prettier
        working-directory: ./apps/backend
        run: npm run format:check

      - name: Lint code
        working-directory: ./apps/backend
        run: npm run lint

      - name: Run unit tests
        working-directory: ./apps/backend
        run: npm run test

      - name: Build project
        working-directory: ./apps/backend
        run: npm run build

  frontend-checks:
    name: Frontend CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: "npm"

      - name: Install frontend dependencies
        working-directory: ./apps/frontend
        run: npm ci

      - name: Prettier
        working-directory: ./apps/frontend
        run: npm run format:check

      - name: Lint code
        working-directory: ./apps/frontend
        run: npm run lint

      - name: Build project
        working-directory: ./apps/frontend
        run: npm run build